import { IFeedback } from 'models/testimonials.model';
import man from '../../../assets/images/backgrounds/man.jpg';

export const fillFeedback: IFeedback[] = [
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
  {
    text: 'I took my car there to get fixed after I was hit and my rear upper controler arm was bent. They gave me the best estimate, and had the work done super quick! The customer service was amazing, and they were very polite and knowledgable!',
    name: 'Silvia R. Brown2',
    function: 'Manager',
    image: man.src,
  },
];
